[client]
showSidebarNavigation = false # Faz desaparecer a barra lateral 

[theme]
primaryColor = "#1c3a6b"             # Cor principal
backgroundColor = "#fafafa"          # Fundo Principal
secondaryBackgroundColor = "#eaebee" # Barra Lateral
textColor = "#000000"                # Texto principal
font = "sans serif"                    # Fonte texto